### ISSUE TITLE
assimp543 still stuck

### ISSUE THREAD

**Issue by traversaro** [conda-forge/dartsim-feedstock#103]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The assimp543 migration is still stuck, and the bot error is:

~~~
        

        linux_aarch64_: Cannot solve the request because of: No candidates were found for dartpy *.

linux_ppc64le_: Cannot solve the request because of: No candidates were found for dartpy *.

osx_arm64_: Cannot solve the request because of: No candidates were found for dartpy *.

win_64_: Cannot solve the request because of: No candidates were found for dartpy *.

        
~~~

See https://conda-forge.org/status/migration/?name=assimp543 and the failing log at https://github.com/regro/cf-scripts/actions/runs/11095180883/job/30823495821 .

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by jslee02** [comment]
@traversaro Do you have any idea how to resolve this issue? It appears that it fails to resolve for platforms where dartpy is not built (i.e., aarch64, ppc64le, osx_arm64, and win).

**Comment by traversaro** [comment]
> @traversaro Do you have any idea how to resolve this issue? It appears that it fails to resolve for platforms where dartpy is not built (i.e., aarch64, ppc64le, osx_arm64, and win).

No idea, I opened https://github.com/regro/cf-scripts/issues/3014 to track the problem.

**Comment by jslee02** [comment]
It seems https://github.com/conda-forge/dartsim-feedstock/pull/105 resolved it! `dartsim` is no longer a blocker in https://conda-forge.org/status/migration/?name=assimp543

**Comment by traversaro** [comment]
Good catch!
