### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by traversaro** [conda-forge/dartsim-feedstock#2]
Windows compilation was initially attempted in the PR of staged-recipes ( https://github.com/conda-forge/staged-recipes/pull/12863 ) but the Windows CI machine was failing in a way that neither me nor @wolfv were able to reproduce locally. Anyhow, there is currently some work in dependencies (https://github.com/conda-forge/assimp-feedstock/pull/13) and upstream (https://github.com/dartsim/dart/pull/1509, https://github.com/dartsim/dart/pull/1510, https://github.com/dartsim/dart/pull/1513) for Windows support, so it is probably better to wait for these efforts to be successful before trying to attempt to add Windows support here.

**Comment by wolfv** [comment]
There was just a new release. Do you know if it improved things on windows?

**Comment by traversaro** [comment]
No, it was a release out of the 6.9 branch, while all the Windows changes are happening on the master branch.

**Comment by traversaro** [comment]
Related issues: 
* https://github.com/dartsim/dart/pull/1513
* https://github.com/dartsim/dart/issues/1522

**Comment by wolfv** [comment]
We have a Windows build now, thanks to @traversaro.
